export const CONTENT_KEYS = [
  { key: "hero", label: "Hero — Photo 01", section: "Accueil" },
  { key: "hero_2", label: "Hero — Photo 02", section: "Accueil" },
  { key: "hero_3", label: "Hero — Photo 03", section: "Accueil" },
  { key: "hero_4", label: "Hero — Photo 04", section: "Accueil" },
  { key: "philosophie", label: "Notre philosophie", section: "Accueil" },
  { key: "creez_produit_vierge", label: "Créez — Produit vierge", section: "Section Créez" },
  { key: "creez_personnalisation", label: "Créez — Personnalisation", section: "Section Créez" },
  { key: "creez_creation_finale", label: "Créez — Création finale", section: "Section Créez" },
  { key: "histoire", label: "Histoire NEMA", section: "Histoire" },
  { key: "situation_look_1", label: "Look 01 — Minimal", section: "NEMA en situation" },
  { key: "situation_look_2", label: "Look 02 — Bold", section: "NEMA en situation" },
  { key: "situation_look_3", label: "Look 03 — Casual", section: "NEMA en situation" },
  { key: "situation_look_4", label: "Look 04 — Signature", section: "NEMA en situation" },
  { key: "apercu_avant", label: "Aperçu IA — Avant", section: "Aperçu IA" },
  { key: "apercu_apres", label: "Aperçu IA — Après", section: "Aperçu IA" },
] as const;
